### ISSUE TITLE
Missing sync-client and sqlite-jdbc dependencies

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-parrot#20]
The gradle build should include the sync-client and sqlite-jdbc dependencies.

**Comment by iamvasuh** [comment]
i want to work on this issue @jbeorse

**Comment by linl33** [comment]
Hi, 

Please go ahead and work on this. 

Thanks

**Comment by jbeorse** [comment]
Solved with: https://github.com/opendatakit/skunkworks-parrot/pull/27

**Comment by linl33** [comment]
The sqlite dependency is still missing.
