### ISSUE TITLE
Firebase database URL is hardcoded. This should be configurable.

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-parrot#21]
[This line](https://github.com/opendatakit/skunkworks-parrot/blob/master/src/main/java/Controller/LoginFormController.java#L147) sets the database URL to https://odk-notifications.firebaseio.com/ but this should be configurable by project

**Comment by hsymphonyk** [comment]
Hello, May I work on this?

**Comment by linl33** [comment]
Hi, 

Please go ahead and work on this. Before you start to implement the change, please post how you intend to fix this issue. There are many ways to make the URL configurable, we want to make sure we can all agree on the design before you spend time on implementing the solution. 

Thanks

**Comment by hsymphonyk** [comment]
Hello @linl33 , Thank you so much. I will surely post the way before implementing it.

**Comment by Saikat2019** [comment]
hello @linl33 to resolve this we can add one more input field in the configuration setting for the firebase url ,so that the user can set it here 

![Screenshot from 2019-03-13 11-51-12](https://user-images.githubusercontent.com/33754597/54304756-d5510a80-45eb-11e9-99e6-38b888d81aa2.png)

will that be okay , if yes please tell me i will start implementing.

**Comment by linl33** [comment]
@Saikat2019, @hsymphonyk has already claimed this issue. Please find another one to work on. 

On the implementation side, adding the url as an option to that panel sounds good.

**Comment by linl33** [comment]
@hsymphonyk Can you give us an update on your progress?

**Comment by hsymphonyk** [comment]
@linl33 extremely sorry for the late reply as my internal exams just got over today, the PR got delayed. I solved the issue in a similar way he had mentioned above. Moreover, I have added a hint button adjacent to the text input field.

**Comment by DreamyPhobic** [comment]
@hridyakrishna As you mentioned in your last comment that you have already solved this issue. If you still have the code, can you please open a PR for it? 
Please let me know as soon as possible. I will be thankful to you.
