### ISSUE TITLE
No instructions for creating Firebase database

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-parrot#24]
This should be documented in the README

**Comment by laddha-adi** [comment]
Step by step instructions for creating a Firebase project can be found [here](https://drive.google.com/file/d/10_9oU_8zrek7lt7BRYmJJwo22rs51uAw/view) . This is already added in the README.

**Comment by jbeorse** [comment]
Ah, you are right. @laddha-adi . Thanks for creating these! I will close this issue.
