### ISSUE TITLE
JavaFX requirement should be documented

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/skunkworks-parrot#25]
The README documentation should mention that JavaFX is required to build the desktop program. Not all JDK builds include it.

**Comment by hsymphonyk** [comment]
Hello, May I work on this?

**Comment by linl33** [comment]
Hi, 

Please go ahead and work on this. 

Thanks

**Comment by hsymphonyk** [comment]
Hello, @linl33  Thank you so much. I will work on it. :)

**Comment by thesherrinford** [comment]
"This project is built using JavaFX and requires JavaFX support for '.fxml' files.
JavaFX is included in Java SE 7 update 6 and higher, up to JDK 10.
But if you are using  JDK11 or higher, please download JavaFX package here(https://gluonhq.com/products/javafx/).
JavaFX is not supported for Java SE 6 and lower."

@linl33 @jbeorse, If I'll add this to the README documentation, will it work?

**Comment by hsymphonyk** [comment]
Hello, @jbeorse , @linl33 , I have solved this issue and created a PR. Please review this. Thank you. :)

**Comment by jbeorse** [comment]
Resolved with: https://github.com/opendatakit/skunkworks-parrot/pull/28
